# Generated by Django 4.0.6 on 2022-07-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bar',
            old_name='age',
            new_name='price',
        ),
    ]
