# Generated by Django 4.0.6 on 2022-07-21 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_age_bar_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='price',
        ),
        migrations.AddField(
            model_name='bar',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='menu',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
