# Generated by Django 4.0.6 on 2022-07-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_bar_price_bar_address_bar_menu_bar_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='rating date')),
                ('rate', models.CharField(choices=[('A', 'Awesome'), ('B', 'Good'), ('C', 'Soso'), ('D', 'Bad')], default='A', max_length=1)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bar')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
