# Generated by Django 4.0.6 on 2022-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(choices=[('A', '⭐️⭐️⭐️⭐️⭐️'), ('B', '⭐️⭐️⭐️⭐️'), ('C', '⭐️⭐️⭐️'), ('D', '⭐️⭐️'), ('E', '⭐️')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='bar',
            name='available',
            field=models.ManyToManyField(to='main_app.available'),
        ),
    ]
